# Generated by Django 5.1.4 on 2024-12-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_remove_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='grading.instructor'),
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
