# Generated by Django 5.1.4 on 2024-12-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_alter_course_department_alter_instructor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
